# Generated by Django 3.1.7 on 2021-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('adj_high', models.FloatField()),
                ('adj_low', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('adj_open', models.FloatField()),
                ('adj_volume', models.FloatField()),
                ('split_factor', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
