# MARKETSTACK API CONFIG
MARKETSTACK_API_KEY = "3388c7248c1e02e4485051f16c81ffc5"
MARKETSTACK_BASE_URL = "http://api.marketstack.com/v1/"

MARKETSTACK_LAST_EOD_URL = MARKETSTACK_BASE_URL + "eod/latest"

# COMPANY TICKER SYMBOLS
APPLE_SYMBOL = "AAPL"
AMAZON_SYMBOL = "AMZN"
TESLA_SYMBOL = "TSLA"
ADOBE_SYMBOL = "ADBE"
MICROSOFT_SYMBOL = "MSFT"
NETFLIX_SYMBOL = "NFLX"


COMPANY_LIST = [
    APPLE_SYMBOL,
    AMAZON_SYMBOL,
    TESLA_SYMBOL,
    ADOBE_SYMBOL,
    MICROSOFT_SYMBOL,
    NETFLIX_SYMBOL
]

NUM_OF_HISTORY_DAYS = 5
